norwoodj/helm-docs

.gitignore, README.md, cmd/helm-docs/chart_finder.go, cmd/helm-docs/chart_info.go, cmd/helm-docs/command_line.go, cmd/helm-docs/generate.go, cmd/helm-docs/main.go, example-chart/README.md, example-chart/values.yaml
Ensures documentation for values that do not specify a default.
Allows for type definition of the nil value by parsing the beginning of the description and looking for the type inside of parentheses, e.g.:
```
replicas:
```
would be parsed as an int value
=> Fix nil values

README.md, example-charts/custom-template/README.md, example-charts/custom-template/values.yaml, pkg/document/values.go, pkg/document/values_test.go, pkg/helm/chart_info.go
This PR adds support for doc comments continuation over multiple lines and default values in doc comments.
The feature was previously discussed here https://github.com/norwoodj/helm-docs/issues/22.
It is a rebirth of the previous PR opened by @Grannath here https://github.com/norwoodj/helm-docs/pull/25. Thanks for the great work !
This adds unit tests, hardens the regexes used to implement doc comments continuation to reduce the risk of mistakenly combining multiple comment lines.
Doc has been updated along with example charts.
=> Add support for custom default values and doc comment continuation

.goreleaser.yml, Dockerfile
This is a try to configure goreleaser to publish docker images.
I don't know much about goreleaser so there are chances that it's not perfect.
Feel completely free to close the PR if it is not something you want to support, no worries.
=> Release docker image

README.md
`--rm` removes the container right after running it, without the need to cleanup
`-u $(id-u)` runs as the current user, removing the need to modify permissions after
=> Improve Docker usage documentation

.pre-commit-hooks.yaml, README.md
While working on https://github.com/norwoodj/helm-docs/issues/48, I noticed that changes to `README.md.gotmpl` did not trigger the `pre-commit` hooks.
The `pre-commit` hooks should be triggered when there is a change to the underlying `README.md.gotmpl` file; otherwise, changes to this template will not trigger a rebuild of the `README.md` file.
=> fix: Updating hook config for README.md.gotmpl

.github/workflows/build.yml, .github/workflows/release.yml, .goreleaser.yml, Makefile
* Adds Github Actions workflows to compile, test and build helm-docs within PRs and all branches
* Adds Goreleaser release automation that is only triggered upon push Git tags
* Adds Deb/Rpm packages to the release artifacts, so that users can install it using `dpkg -i` and the rpm equivalent. No additional dependency besides `goreleaser` is necessary for local development. The packages will install the binary in `/usr/local/bin` by default (see https://goreleaser.com/customization/#NFPM)
* Configures artifact checksum signing with GPG, so users can verify the downloads (instructions to set up below)
* Adds an additional Makefile target `dist`
* [GitHub Actions usage is free for public repositories](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/ab …
=> Add CI/CD pipelines and deb/rpm packaging options

.github/workflows/release.yml
This release action (https://github.com/norwoodj/helm-docs/runs/955815074) failed because the token is wrong.
The token needs to be one that has access to write to the https://github.com/norwoodj/homebrew-tap repository. Using the default `secrets.GITHUB_TOKEN` token is wrong because it only has access to write to the _current_ repository, and nothing else.
@norwoodj Can you create a personal access token with the `repo` scope enabled as it says in the instructions here please (https://goreleaser.com/environment/#api-tokens) ? It should go in a secret named `NORWOODJ_ORG_TOKEN `.
=> fix: GitHub token for Homebrew tap

.goreleaser.yml
- Resolves https://github.com/norwoodj/helm-docs/issues/51, adding not only Windows support, but also adding ARM / ARM64 types as well.
- Resolves the deprecation notice that comes with using the old `github` keyword in the `brews` section (see here: https://goreleaser.com/deprecations/#brewsgithub).
=> Adding more OS and architecture types

README.md, example-charts/full-template/README.md, example-charts/full-template/README.md.gotmpl, pkg/document/template.go
This PR adds a `badgesSection` template. It's useful if you want to define a custom set of badges and don't want to copy-paste them to every template.
For example: I usually add a kubeVersion and an artifact hub badge as well.
PS. I wasn't sure how the examples are supposed to be updated. Using the locally built binary generated a bunch of unrelated changes.
=> Add badges section

pkg/document/template.go, pkg/helm/chart_info.go
This allows for charts using dependencies to have documentation showing their aliases (if defined).
This is handy when several dependencies use the same chart with different aliases.
Before 
| Repository | Name | Version |
|------------|------|---------| 
| repo| dependency1 | 0.1.0 |   
| repo | sharedchart | 0.1.0|   
| repo | sharedchart | 0.1.0|   
| repo | sharedchart | 0.1.0|   
after
| Repository | Name | Version |
|------------|------|---------| 
| repo| dependency1 | 0.1.0 |   
| repo | dependency2(sharedchart) | 0.1.0|   
| repo | dependency3(sharedchart) | 0.1.0|   
| repo | dependency4(sharedchart) | 0.1.0|
=> Parse requirement's alias and display "alias(name)" if 'alias' not empty

pkg/document/values.go, pkg/document/values_test.go
Hi there!
Thanks for the awesome tool!
I discovered a bug, where the @default isn't picked up if the variable has no value.
This PR fixes this bug by only setting the `description.Default` to `nil` if there is no `autoDescription.Default`.
=> fix: fixes @default for variables without value

README.md
It is now possible to install `helm-docs` using [scoop](https://scoop/sh) on Windows. See ScoopInstaller/Main#1938 for the details.
=> Extend README Installation section with scoop alternative for Windows

.github/workflows/build.yml, .github/workflows/release.yml, .goreleaser.yml
Solves https://github.com/norwoodj/helm-docs/issues/94.
- The GoReleaser action and the Go version are updated to support builds for Apple Silicon
- Multi-arch Docker images have been added
- https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
=> Support Apple M1 / Multi-Arch Docker builds

pkg/document/values.go, pkg/document/values_test.go
=> fix type definition when description is empty

pkg/document/values.go, pkg/document/values_test.go, pkg/helm/comment.go
Attempts to fix #96. It seems to work for a complex chart I tested with on which the same issue was being observed. I've also added a couple tests.
=> Consider only the last group of comments starting with '# --'.

cmd/helm-docs/command_line.go, pkg/helm/chart_info.go
Not all values files are named `values.yaml` so it would be handy to be able to point `helm-docs` to the actual values file if it is not named according to the expected convention. Many tools, including `helm` itself, support a `-f` short option to which you can supply a relative filesystem path that refers to the values file you'd like to load. This change set makes `helm-docs` support that same CLI interface.
=> Add option for a values file named other than `values.yaml`.

pkg/document/template.go
Markdown linters like markdownlint fail by default on raw URLs. Wrap
maintainer table URLs in angle brackets to follow this norm and avoid
failures.
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>
=> Avoid raw URLs in maintainer tables

cmd/helm-docs/command_line.go, pkg/document/model.go, pkg/document/values.go, pkg/helm/comment.go
This way, by adding the `ignore-non-descriptions` flag, values without description will be excluded from the table.
The default will remain as it is now.
=> adding ignore-non-descriptions flag

README.md, cmd/helm-docs/command_line.go, cmd/helm-docs/main.go
Usefull for generating umbrella chart doc with dependency values
`document-dependency-values` flag includes dependency values
In `chart-to-generate` you can list charts that needs to be generated
without generating doc for each dependency.
=> Add an option to list charts to generate

example-charts/files-values/Chart.yaml, example-charts/files-values/README.md, example-charts/files-values/README.md.gotmpl, example-charts/files-values/somefile.yaml, example-charts/files-values/templates/resource1.yaml, example-charts/files-values/templates/resource2.yaml, example-charts/files-values/values.yaml, go.mod, go.sum, pkg/document/files.go, pkg/document/files_test.go, pkg/document/model.go
Related to #107 its an initial go at adding a basic .Files value into the template context.
Is near identical to the actual Helm implementation albeit a simplified one.
For this I've added the `github.com/gobwas/glob` dependency which helm also pulls in.
=> Added Helm .Files

.github/workflows/build.yml, .github/workflows/release.yml, .goreleaser.yml, README.md, cmd/helm-docs/command_line.go, cmd/helm-docs/main.go, example-charts/fully-documented/Chart.yaml, example-charts/fully-documented/README.md, example-charts/fully-documented/values.yaml, pkg/helm/chart_info.go, pkg/helm/chart_info_test.go
This PR introduce three options for the helm-docs executable:
- an option to fail if there are some values with no documentation
- an option to ignore some values without documentation by regex
- an option to ignore some values without documentation by name
Addresses #169
=> Issue 169: Introduce strict linting options of values and exclusions

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/PULL_REQUEST_TEMPLATE/general_template.md, CONTRIBUTING.md, SECURITY.md, code-of-conduct.md
> **OBS.: Unfornately the commit message pushed wasn't correct, sorry about that. Reference the following text as a possible substitute.**
Making simple changes to make contributing to the project better and easier.
- Refining guidelines for _contribution_ and defining _security reports_ and the repository _code of conduct_.
- Creating issue templates for **bugs** and **feature** requests.
- Creating a general template for **pull requests**.
I used the following resources and projects:
- https://opensource.guide/
- https://www.talater.com/open-source-templates/#/page/1
- https://github.com/stevemao/github-issue-templates
- https://github.com/devspace/awesome-github-templates
- https://raw.githubusercontent.com/microsoft/.github/main/SECURITY.md
- https://github.com/appium/appium/
- …
=> docs: improving community standards

.pre-commit-hooks.yaml, README.md
Simple PR that adds support for using the pre-build Docker container image rather than requiring users to install the binary or build the golang package from source.
Tested locally and works with this `.pre-commit-config.yaml`:
```yaml
---
repos:
- repo: https://github.com/Labelbox/helm-docs
rev:  65f1d83 # add-docker-to-pre-commit-hooks
hooks:
- id: helm-docs-container
args:
- --chart-search-root=charts
```
Related:
https://github.com/pre-commit/pre-commit/issues/2968
=> Add containerized pre-commit hook

pkg/document/values.go, pkg/document/values_test.go
`parseNilValueType()` was not including NotationType in its output.
Fixes norwoodj/helm-docs#183
=> Copy NotationType in Nil Values

.goreleaser.yml
Update to use SPDX ID for better understanding. (also relates to https://github.com/Homebrew/homebrew-core/pull/161554)
=> license: update to use spdx id

go.mod
Very minor, but on macos M1, I got this issue https://github.com/golang/go/issues/65568
```
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
=> chore: set go version to 1.22.0

pkg/document/template.go, pkg/util/funcs.go
Adds `toYaml` and `fromYaml` functions from helm src
=> feat: add toYaml and fromYaml to functions map

example-charts/use-yaml-file/Chart.yaml, example-charts/use-yaml-file/README.md, example-charts/use-yaml-file/README.md.gotmpl, example-charts/use-yaml-file/values.yaml, go.mod
Add example for PR https://github.com/norwoodj/helm-docs/pull/176
Add toYaml , fromYaml gotemplate functions.
=> feat: add toYaml and fromYaml example

.github/workflows/build.yml, .github/workflows/release.yml
This PR updates the referenced GitHub actions to use the digests rather than tags. It also switches to using the Docker Hub login action over using the CLI directly.
CC @norwoodj
=> chore: Changed to use digests for GH actions
